version: '3.8'

services:
    postgres:
        image: postgres:15
        container_name: embedded_postgres
        environment:
            POSTGRES_USER: postgres_user
            POSTGRES_PASSWORD: postgres_password
            POSTGRES_DB: embedded_db
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

    backend:
        build: .
        container_name: embedded_backend
        ports:
            - '3000:3000'
        depends_on:
            - postgres
        environment:
            - DATABASE_URL=postgresql://postgres_user:postgres_password@postgres:5432/embedded_db?schema=public
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/image-captioning.json
            - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
            - GOOGLE_LOCATION=${GOOGLE_LOCATION}
        volumes:
            - ./uploads:/usr/src/app/uploads
            - ./image-captioning.json:/usr/src/app/image-captioning.json

volumes:
    pgdata:
