version: '3.8'

services:
    postgres:
        image: postgres:15
        container_name: embedded_postgres
        environment:
            POSTGRES_USER: postgres_user
            POSTGRES_PASSWORD: postgres_password
            POSTGRES_DB: embedded_db
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
